import BernsteinObstacle

#check BernsteinObstacle.eval_affineBarycentric
#check BernsteinObstacle.totalDegree_affineBarycentric_le
#check BernsteinObstacle.totalDegree_affineBernsteinPolynomial_le
#check BernsteinObstacle.affineBernsteinPolynomial_mem_restrictTotalDegree
#check BernsteinObstacle.eval_affineBernsteinPolynomial
#check BernsteinObstacle.eval_affineBernsteinPolynomial_eq_simplexBasis

#print axioms BernsteinObstacle.eval_affineBarycentric
#print axioms BernsteinObstacle.totalDegree_affineBarycentric_le
#print axioms BernsteinObstacle.totalDegree_affineBernsteinPolynomial_le
#print axioms BernsteinObstacle.affineBernsteinPolynomial_mem_restrictTotalDegree
#print axioms BernsteinObstacle.eval_affineBernsteinPolynomial
#print axioms BernsteinObstacle.eval_affineBernsteinPolynomial_eq_simplexBasis
