import BernsteinObstacle

#check BernsteinObstacle.eval_affineBarycentric
#check BernsteinObstacle.totalDegree_affineBarycentric_le
#check BernsteinObstacle.totalDegree_affineBernsteinPolynomial_le
#check BernsteinObstacle.affineBernsteinPolynomial_mem_restrictTotalDegree
#check BernsteinObstacle.eval_affineBernsteinPolynomial
#check BernsteinObstacle.eval_affineBernsteinPolynomial_eq_simplexBasis
#check BernsteinObstacle.affineBernsteinExponent_sum
#check BernsteinObstacle.affineBernsteinCoefficient_pos
#check BernsteinObstacle.affineBernsteinCoefficient_ne_zero
#check BernsteinObstacle.prod_X_pow_eq_affineBernsteinMonomial
#check BernsteinObstacle.affineBernsteinPolynomial_factor
#check BernsteinObstacle.coeff_zero_affineBarycentric_last_pow
#check BernsteinObstacle.coeff_affineBernsteinPolynomial_at_own_exponent
#check BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_not_le
#check BernsteinObstacle.affineBernsteinRank_eq_exponent_sum
#check BernsteinObstacle.affineBernsteinExponent_injective
#check BernsteinObstacle.affineBernsteinRank_le_of_exponent_le
#check BernsteinObstacle.affineBernsteinExponent_eq_of_le_of_rank_eq
#check BernsteinObstacle.affineBernsteinExponent_not_le_of_rank_lt
#check BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_rank_lt
#check BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_rank_eq_of_ne
#check BernsteinObstacle.affineBernsteinPolynomial_linearIndependent
#check BernsteinObstacle.affineBernsteinVector_linearIndependent
#check BernsteinObstacle.affineBernsteinBasis_apply
#check BernsteinObstacle.span_affineBernsteinVector_eq_top
#check BernsteinObstacle.affineBernsteinBasis_sum_repr
#check BernsteinObstacle.affineBernsteinCollocationEquiv_apply
#check BernsteinObstacle.affineBernsteinCollocation_injective
#check BernsteinObstacle.affineBernsteinCollocation_surjective
#check BernsteinObstacle.existsUnique_bernsteinCoefficients_with_latticeValues

#print axioms BernsteinObstacle.eval_affineBarycentric
#print axioms BernsteinObstacle.totalDegree_affineBarycentric_le
#print axioms BernsteinObstacle.totalDegree_affineBernsteinPolynomial_le
#print axioms BernsteinObstacle.affineBernsteinPolynomial_mem_restrictTotalDegree
#print axioms BernsteinObstacle.eval_affineBernsteinPolynomial
#print axioms BernsteinObstacle.eval_affineBernsteinPolynomial_eq_simplexBasis
#print axioms BernsteinObstacle.affineBernsteinExponent_sum
#print axioms BernsteinObstacle.affineBernsteinCoefficient_pos
#print axioms BernsteinObstacle.affineBernsteinCoefficient_ne_zero
#print axioms BernsteinObstacle.prod_X_pow_eq_affineBernsteinMonomial
#print axioms BernsteinObstacle.affineBernsteinPolynomial_factor
#print axioms BernsteinObstacle.coeff_zero_affineBarycentric_last_pow
#print axioms BernsteinObstacle.coeff_affineBernsteinPolynomial_at_own_exponent
#print axioms BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_not_le
#print axioms BernsteinObstacle.affineBernsteinRank_eq_exponent_sum
#print axioms BernsteinObstacle.affineBernsteinExponent_injective
#print axioms BernsteinObstacle.affineBernsteinRank_le_of_exponent_le
#print axioms BernsteinObstacle.affineBernsteinExponent_eq_of_le_of_rank_eq
#print axioms BernsteinObstacle.affineBernsteinExponent_not_le_of_rank_lt
#print axioms BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_rank_lt
#print axioms BernsteinObstacle.coeff_affineBernsteinPolynomial_eq_zero_of_rank_eq_of_ne
#print axioms BernsteinObstacle.affineBernsteinPolynomial_linearIndependent
#print axioms BernsteinObstacle.affineBernsteinVector_linearIndependent
#print axioms BernsteinObstacle.affineBernsteinBasis_apply
#print axioms BernsteinObstacle.span_affineBernsteinVector_eq_top
#print axioms BernsteinObstacle.affineBernsteinBasis_sum_repr
#print axioms BernsteinObstacle.affineBernsteinCollocationEquiv_apply
#print axioms BernsteinObstacle.affineBernsteinCollocation_injective
#print axioms BernsteinObstacle.affineBernsteinCollocation_surjective
#print axioms BernsteinObstacle.existsUnique_bernsteinCoefficients_with_latticeValues
