import BernsteinObstacle.PhysicalOddMeshQuadratic
import BernsteinObstacle.PhysicalCoefficientDistance
import BernsteinObstacle.PhysicalQuadraticH1
import BernsteinObstacle.GreenRecoverySequence
import BernsteinObstacle.GreenTraceDefect
import BernsteinObstacle.GreenInterpolationRate
import BernsteinObstacle.OneStepFittedAFEM
import BernsteinObstacle.OneStepFittedAFEMBestError

#print axioms BernsteinObstacle.xSquaredCellCoeff_curve_eq
#print axioms BernsteinObstacle.centralPhysicalCoeff_even_center_neg
#print axioms BernsteinObstacle.physicalRepairCoeff_curve_eq
#print axioms BernsteinObstacle.evenPhysicalCoefficient_bestApproximation_lower
#print axioms BernsteinObstacle.evenPhysicalCoefficient_bestApproximation_pos
#print axioms BernsteinObstacle.intervalIntegral_quadraticRepairH1Density
#print axioms BernsteinObstacle.intervalIntegral_quadraticRepairError_H1_sq_le
#print axioms BernsteinObstacle.greenCentralValue_tendsto_one
#print axioms BernsteinObstacle.greenTraceDefect_tendsto_zero_of_sqrt_bound
#print axioms BernsteinObstacle.greenProfileNorm_tendsto_of_linear_bound
#print axioms BernsteinObstacle.normalizedQuadraticError_greenProfile_tendsto_of_quantitative_bounds
#print axioms BernsteinObstacle.oneMinusQuadraticCoeff_curve_eq
#print axioms BernsteinObstacle.oneStepFittedAFEM_exact_feasible_and_shapeRegular
#print axioms BernsteinObstacle.oneStepFittedAFEM_bestApproximationError_eq_zero
#print axioms BernsteinObstacle.oneStepFittedAFEM_complete
