import BernsteinObstacle.PhysicalOddMeshQuadratic
import BernsteinObstacle.PhysicalCoefficientDistance
import BernsteinObstacle.PhysicalQuadraticH1
import BernsteinObstacle.PhysicalNormTransport
import BernsteinObstacle.GreenRecoverySequence
import BernsteinObstacle.GreenTraceDefect
import BernsteinObstacle.GreenInterpolationRate
import BernsteinObstacle.GreenOddMeshClosedLimit
import BernsteinObstacle.OneStepFittedAFEM
import BernsteinObstacle.OneStepFittedAFEMBestError
import BernsteinObstacle.GeneralContactFittedAFEM

#print axioms BernsteinObstacle.xSquaredCellCoeff_curve_eq
#print axioms BernsteinObstacle.centralPhysicalCoeff_even_center_neg
#print axioms BernsteinObstacle.physicalRepairCoeff_curve_eq
#print axioms BernsteinObstacle.evenPhysicalCoefficient_bestApproximation_lower
#print axioms BernsteinObstacle.evenPhysicalCoefficient_bestApproximation_pos
#print axioms BernsteinObstacle.intervalIntegral_quadraticRepairH1Density
#print axioms BernsteinObstacle.intervalIntegral_quadraticRepairError_H1_sq_le
#print axioms BernsteinObstacle.bestApproximationError_transport_sandwich
#print axioms BernsteinObstacle.physical_secondOrder_saturation_of_basisEquiv
#print axioms BernsteinObstacle.greenCentralValue_tendsto_one
#print axioms BernsteinObstacle.greenTraceDefect_tendsto_zero_of_sqrt_bound
#print axioms BernsteinObstacle.greenProfileNorm_tendsto_of_sqrt_bound
#print axioms BernsteinObstacle.oddGreenInterpolantEnergyClosed_tendsto
#print axioms BernsteinObstacle.oddGreenInterpolantNormClosed_tendsto
#print axioms BernsteinObstacle.normalizedQuadraticError_greenProfile_tendsto_with_oddClosedNorm
#print axioms BernsteinObstacle.oneMinusQuadraticCoeff_curve_eq
#print axioms BernsteinObstacle.oneStepFittedAFEM_exact_feasible_and_shapeRegular
#print axioms BernsteinObstacle.oneStepFittedAFEM_bestApproximationError_eq_zero
#print axioms BernsteinObstacle.oneStepFittedAFEM_complete
#print axioms BernsteinObstacle.generalContactFitted_bestApproximationError_eq_zero
#print axioms BernsteinObstacle.generalContactFittedAFEM_complete
