import BernsteinObstacle.PhysicalOddMeshQuadratic
import BernsteinObstacle.GreenRecoverySequence
import BernsteinObstacle.OneStepFittedAFEM
import BernsteinObstacle.SimplexQuadraticContact

#print axioms BernsteinObstacle.xSquaredCellCoeff_curve_eq
#print axioms BernsteinObstacle.centralPhysicalCoeff_even_center_neg
#print axioms BernsteinObstacle.physicalRepairCoeff_curve_eq
#print axioms BernsteinObstacle.greenProfile_exact_limit_from_recovery
#print axioms BernsteinObstacle.normalizedQuadraticError_greenProfile_tendsto
#print axioms BernsteinObstacle.oneMinusQuadraticCoeff_curve_eq
#print axioms BernsteinObstacle.oneStepFittedAFEM_exact_feasible_and_shapeRegular
#print axioms BernsteinObstacle.simplexQuadraticNormal_exact_and_nonnegative
