import BernsteinObstacle.AssembledHilbertTransfer

#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.hilbertVISolutions_strongConvergence
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.mosco_and_hilbertVISolutions_strongConvergence

#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.hilbertVISolutions_strongConvergence
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.mosco_and_hilbertVISolutions_strongConvergence
