import BernsteinObstacle

#check BernsteinObstacle.basis_nonneg
#check BernsteinObstacle.basis_sum_eq_one
#check BernsteinObstacle.curve_nonneg
#check BernsteinObstacle.curve_mem_Icc
#check BernsteinObstacle.curve_le_clipped_curve
#check BernsteinObstacle.noPenetration_of_nonnegative_coefficients
#check BernsteinObstacle.noPenetration_after_clipping
#check BernsteinObstacle.coefficientCone_convex
#check BernsteinObstacle.clipCoefficients_mem
#check BernsteinObstacle.clipCoefficients_idem
#check BernsteinObstacle.clipCoefficients_minimal
#check BernsteinObstacle.basis3_nonneg
#check BernsteinObstacle.field3_nonneg
#check BernsteinObstacle.clipped_field3_nonneg
#check BernsteinObstacle.noPenetration3_of_nonnegative_coefficients
#check BernsteinObstacle.noPenetration3_after_clipping
#check BernsteinObstacle.simplexBasis_nonneg
#check BernsteinObstacle.simplexField_nonneg
#check BernsteinObstacle.clipped_simplexField_nonneg
#check BernsteinObstacle.simplex_noPenetration_of_nonnegative_coefficients
#check BernsteinObstacle.simplex_noPenetration_after_clipping
#check BernsteinObstacle.simplexBasisNat_nonneg
#check BernsteinObstacle.simplexBasisNat_sum_eq_one
#check BernsteinObstacle.simplexFieldNat_nonneg
#check BernsteinObstacle.simplexFieldNat_mem_Icc

#print axioms BernsteinObstacle.basis_nonneg
#print axioms BernsteinObstacle.basis_sum_eq_one
#print axioms BernsteinObstacle.curve_nonneg
#print axioms BernsteinObstacle.curve_mem_Icc
#print axioms BernsteinObstacle.curve_le_clipped_curve
#print axioms BernsteinObstacle.noPenetration_of_nonnegative_coefficients
#print axioms BernsteinObstacle.noPenetration_after_clipping
#print axioms BernsteinObstacle.coefficientCone_convex
#print axioms BernsteinObstacle.clipCoefficients_mem
#print axioms BernsteinObstacle.clipCoefficients_idem
#print axioms BernsteinObstacle.clipCoefficients_minimal
#print axioms BernsteinObstacle.basis3_nonneg
#print axioms BernsteinObstacle.field3_nonneg
#print axioms BernsteinObstacle.clipped_field3_nonneg
#print axioms BernsteinObstacle.noPenetration3_of_nonnegative_coefficients
#print axioms BernsteinObstacle.noPenetration3_after_clipping
#print axioms BernsteinObstacle.simplexBasis_nonneg
#print axioms BernsteinObstacle.simplexField_nonneg
#print axioms BernsteinObstacle.clipped_simplexField_nonneg
#print axioms BernsteinObstacle.simplex_noPenetration_of_nonnegative_coefficients
#print axioms BernsteinObstacle.simplex_noPenetration_after_clipping
#print axioms BernsteinObstacle.simplexBasisNat_nonneg
#print axioms BernsteinObstacle.simplexBasisNat_sum_eq_one
#print axioms BernsteinObstacle.simplexFieldNat_nonneg
#print axioms BernsteinObstacle.simplexFieldNat_mem_Icc
