import BernsteinObstacle

#check BernsteinObstacle.basis_nonneg
#check BernsteinObstacle.basis_sum_eq_one
#check BernsteinObstacle.curve_nonneg
#check BernsteinObstacle.curve_mem_Icc
#check BernsteinObstacle.curve_le_clipped_curve
#check BernsteinObstacle.noPenetration_of_nonnegative_coefficients
#check BernsteinObstacle.noPenetration_after_clipping
#check BernsteinObstacle.coefficientCone_convex
#check BernsteinObstacle.clipCoefficients_mem
#check BernsteinObstacle.clipCoefficients_idem
#check BernsteinObstacle.clipCoefficients_minimal
#check BernsteinObstacle.clipCoefficients_sqDist_minimal
#check BernsteinObstacle.clipCoefficients_eq_self_iff
#check BernsteinObstacle.coefficientSqDist_clip_eq_zero_iff
#check BernsteinObstacle.basis3_nonneg
#check BernsteinObstacle.field3_nonneg
#check BernsteinObstacle.clipped_field3_nonneg
#check BernsteinObstacle.noPenetration3_of_nonnegative_coefficients
#check BernsteinObstacle.noPenetration3_after_clipping
#check BernsteinObstacle.simplexBasis_nonneg
#check BernsteinObstacle.simplexField_nonneg
#check BernsteinObstacle.clipped_simplexField_nonneg
#check BernsteinObstacle.simplex_noPenetration_of_nonnegative_coefficients
#check BernsteinObstacle.simplex_noPenetration_after_clipping
#check BernsteinObstacle.simplexBasisNat_nonneg
#check BernsteinObstacle.simplexBasisNat_sum_eq_one
#check BernsteinObstacle.simplexFieldNat_nonneg
#check BernsteinObstacle.simplexFieldNat_mem_Icc
#check BernsteinObstacle.clipped_local_coeff_eq_of_shared
#check BernsteinObstacle.clipped_globalSimplexField_nonneg
#check BernsteinObstacle.global_noPenetration_after_clipping
#check BernsteinObstacle.boundary_zero_after_clipping
#check BernsteinObstacle.discreteEnergy_difference_identity
#check BernsteinObstacle.half_error_energy_le
#check BernsteinObstacle.coercive_error_le_energy
#check BernsteinObstacle.vi_solution_is_energy_minimizer
#check BernsteinObstacle.vi_solution_half_error_le_energy_gap
#check BernsteinObstacle.vi_solution_coercive_error_le_energy_gap
#check BernsteinObstacle.moscoConverges_const_self
#check BernsteinObstacle.mosco_recovery
#check BernsteinObstacle.mosco_weak_limit

#print axioms BernsteinObstacle.basis_nonneg
#print axioms BernsteinObstacle.basis_sum_eq_one
#print axioms BernsteinObstacle.curve_nonneg
#print axioms BernsteinObstacle.curve_mem_Icc
#print axioms BernsteinObstacle.curve_le_clipped_curve
#print axioms BernsteinObstacle.noPenetration_of_nonnegative_coefficients
#print axioms BernsteinObstacle.noPenetration_after_clipping
#print axioms BernsteinObstacle.coefficientCone_convex
#print axioms BernsteinObstacle.clipCoefficients_mem
#print axioms BernsteinObstacle.clipCoefficients_idem
#print axioms BernsteinObstacle.clipCoefficients_minimal
#print axioms BernsteinObstacle.clipCoefficients_sqDist_minimal
#print axioms BernsteinObstacle.clipCoefficients_eq_self_iff
#print axioms BernsteinObstacle.coefficientSqDist_clip_eq_zero_iff
#print axioms BernsteinObstacle.basis3_nonneg
#print axioms BernsteinObstacle.field3_nonneg
#print axioms BernsteinObstacle.clipped_field3_nonneg
#print axioms BernsteinObstacle.noPenetration3_of_nonnegative_coefficients
#print axioms BernsteinObstacle.noPenetration3_after_clipping
#print axioms BernsteinObstacle.simplexBasis_nonneg
#print axioms BernsteinObstacle.simplexField_nonneg
#print axioms BernsteinObstacle.clipped_simplexField_nonneg
#print axioms BernsteinObstacle.simplex_noPenetration_of_nonnegative_coefficients
#print axioms BernsteinObstacle.simplex_noPenetration_after_clipping
#print axioms BernsteinObstacle.simplexBasisNat_nonneg
#print axioms BernsteinObstacle.simplexBasisNat_sum_eq_one
#print axioms BernsteinObstacle.simplexFieldNat_nonneg
#print axioms BernsteinObstacle.simplexFieldNat_mem_Icc
#print axioms BernsteinObstacle.clipped_local_coeff_eq_of_shared
#print axioms BernsteinObstacle.clipped_globalSimplexField_nonneg
#print axioms BernsteinObstacle.global_noPenetration_after_clipping
#print axioms BernsteinObstacle.boundary_zero_after_clipping
#print axioms BernsteinObstacle.discreteEnergy_difference_identity
#print axioms BernsteinObstacle.half_error_energy_le
#print axioms BernsteinObstacle.coercive_error_le_energy
#print axioms BernsteinObstacle.vi_solution_is_energy_minimizer
#print axioms BernsteinObstacle.vi_solution_half_error_le_energy_gap
#print axioms BernsteinObstacle.vi_solution_coercive_error_le_energy_gap
#print axioms BernsteinObstacle.moscoConverges_const_self
#print axioms BernsteinObstacle.mosco_recovery
#print axioms BernsteinObstacle.mosco_weak_limit
