import BernsteinObstacle

-- Convex-target, metric-projection, and multiplier-vanishing regression targets.

#check BernsteinObstacle.smul_mem_convex_of_zero_mem
#check BernsteinObstacle.convex_pointwiseConvexConstraint
#check BernsteinObstacle.simplexVectorFieldNat_mem_convex
#check BernsteinObstacle.simplexVectorFieldNat_pointwise_feasible
#check BernsteinObstacle.convex_convexCoefficientSet
#check BernsteinObstacle.repaired_simplexVectorFieldNat_mem_convex
#check BernsteinObstacle.repaired_simplexVectorFieldNat_pointwise_feasible
#check BernsteinObstacle.convexMetricProjection
#check BernsteinObstacle.convexMetricProjection_mem
#check BernsteinObstacle.convexMetricProjection_norm_eq_iInf
#check BernsteinObstacle.convexMetricProjection_inner_le_zero
#check BernsteinObstacle.metricProjected_simplexVectorFieldNat_pointwise_feasible
#check BernsteinObstacle.multiplierVanishingExponent
#check BernsteinObstacle.grandInterfaceVanishingExponent
#check BernsteinObstacle.threeHalvesContactLaw_with_zero_multiplierVanishing
#check BernsteinObstacle.balancedContactOrderWithVanishing
#check BernsteinObstacle.balancedContactOrderWithVanishing_equalizes
#check BernsteinObstacle.balancedContactOrderWithVanishing_zero

#print axioms BernsteinObstacle.smul_mem_convex_of_zero_mem
#print axioms BernsteinObstacle.convex_pointwiseConvexConstraint
#print axioms BernsteinObstacle.simplexVectorFieldNat_mem_convex
#print axioms BernsteinObstacle.simplexVectorFieldNat_pointwise_feasible
#print axioms BernsteinObstacle.convex_convexCoefficientSet
#print axioms BernsteinObstacle.repaired_simplexVectorFieldNat_mem_convex
#print axioms BernsteinObstacle.repaired_simplexVectorFieldNat_pointwise_feasible
#print axioms BernsteinObstacle.convexMetricProjection
#print axioms BernsteinObstacle.convexMetricProjection_mem
#print axioms BernsteinObstacle.convexMetricProjection_norm_eq_iInf
#print axioms BernsteinObstacle.convexMetricProjection_inner_le_zero
#print axioms BernsteinObstacle.metricProjected_simplexVectorFieldNat_pointwise_feasible
#print axioms BernsteinObstacle.multiplierVanishingExponent
#print axioms BernsteinObstacle.grandInterfaceVanishingExponent
#print axioms BernsteinObstacle.threeHalvesContactLaw_with_zero_multiplierVanishing
#print axioms BernsteinObstacle.balancedContactOrderWithVanishing
#print axioms BernsteinObstacle.balancedContactOrderWithVanishing_equalizes
#print axioms BernsteinObstacle.balancedContactOrderWithVanishing_zero
