import BernsteinObstacle

-- Terminal audit for the finite assembled recovery-to-minimizer convergence layer.

#check BernsteinObstacle.coefficientNormSq_tendsto_zero_of_scaled_le
#check BernsteinObstacle.stronglyConverges_of_recovery_scaledEnergyGap
#check BernsteinObstacle.assemblyMosco_recovery_closeness_implies_strongConvergence
#check BernsteinObstacle.assembledClippedRecovery_implies_strongConvergence
#check BernsteinObstacle.assemblyRecoveryOperator_closeness_implies_strongConvergence
#check BernsteinObstacle.assembledVISolutions_strongConvergence_of_energyGap
#check BernsteinObstacle.assembledVISolutions_strongConvergence_of_clippedRecoveryEnergyGap

#print axioms BernsteinObstacle.coefficientNormSq_tendsto_zero_of_scaled_le
#print axioms BernsteinObstacle.stronglyConverges_of_recovery_scaledEnergyGap
#print axioms BernsteinObstacle.assemblyMosco_recovery_closeness_implies_strongConvergence
#print axioms BernsteinObstacle.assembledClippedRecovery_implies_strongConvergence
#print axioms BernsteinObstacle.assemblyRecoveryOperator_closeness_implies_strongConvergence
#print axioms BernsteinObstacle.assembledVISolutions_strongConvergence_of_energyGap
#print axioms BernsteinObstacle.assembledVISolutions_strongConvergence_of_clippedRecoveryEnergyGap
