import BernsteinObstacle

#check BernsteinObstacle.eventualIndex_spec
#check BernsteinObstacle.EventuallySobolevFEMRecoveryData.stage_le_threshold
#check BernsteinObstacle.EventuallySobolevFEMRecoveryData.recovery_mem_after_threshold
#check BernsteinObstacle.EventuallySobolevFEMRecoveryData.recovery_close_after_threshold
#check BernsteinObstacle.EventuallySobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.EventuallySobolevFEMRecoveryData.minimizers_strongConvergence

#print axioms BernsteinObstacle.eventualIndex_spec
#print axioms BernsteinObstacle.EventuallySobolevFEMRecoveryData.stage_le_threshold
#print axioms BernsteinObstacle.EventuallySobolevFEMRecoveryData.recovery_mem_after_threshold
#print axioms BernsteinObstacle.EventuallySobolevFEMRecoveryData.recovery_close_after_threshold
#print axioms BernsteinObstacle.EventuallySobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.EventuallySobolevFEMRecoveryData.minimizers_strongConvergence
