import BernsteinObstacle

#check BernsteinObstacle.zero_mem_assemblyFeasibleSet
#check BernsteinObstacle.assemblyFeasibleSet_convex
#check BernsteinObstacle.clipCoefficients_sqDist_minimal_assembly
#check BernsteinObstacle.clipCoefficients_projection_inequality_assembly
#check BernsteinObstacle.localFaceTrace_eq_sharedFaceTrace
#check BernsteinObstacle.localFaceTrace_eq_of_commonFace
#check BernsteinObstacle.clipped_localFaceTrace_eq_of_commonFace
#check BernsteinObstacle.sharedBoundaryFaceTrace_eq_zero
#check BernsteinObstacle.localBoundaryFaceTrace_eq_zero
#check BernsteinObstacle.clippedRecovery_localBoundaryFaceTrace_eq_zero
#check BernsteinObstacle.assemblyFeasibleSet_weaklySequentiallyClosed
#check BernsteinObstacle.assemblyFeasibleSet_mosco_const
#check BernsteinObstacle.assemblyFeasibleSet_identity_recovery
#check BernsteinObstacle.assemblyMosco_recovery_closeness_implies_strongConvergence
#check BernsteinObstacle.assembledClippedRecovery_implies_strongConvergence
#check BernsteinObstacle.assemblyRecoveryOperator_closeness_implies_strongConvergence
#check BernsteinObstacle.norm_sq_le_coefficientNormSq
#check BernsteinObstacle.norm_le_sqrt_coefficientNormSq
#check BernsteinObstacle.stronglyConverges_zero_of_coefficientNormSq_tendsto_zero
#check BernsteinObstacle.stronglyConverges_of_recovery_coefficientNormSq
#check BernsteinObstacle.stronglyConverges_of_recovery_coefficientNormSq_bound
#check BernsteinObstacle.coefficientNormSq_sub_comm
#check BernsteinObstacle.coefficientNormSq_tendsto_zero_of_scaled_le
#check BernsteinObstacle.stronglyConverges_of_recovery_scaledEnergyGap
#check BernsteinObstacle.assembledVISolutions_strongConvergence_of_energyGap
#check BernsteinObstacle.assembledVISolutions_strongConvergence_of_clippedRecoveryEnergyGap

#print axioms BernsteinObstacle.zero_mem_assemblyFeasibleSet
#print axioms BernsteinObstacle.assemblyFeasibleSet_convex
#print axioms BernsteinObstacle.clipCoefficients_sqDist_minimal_assembly
#print axioms BernsteinObstacle.clipCoefficients_projection_inequality_assembly
#print axioms BernsteinObstacle.localFaceTrace_eq_sharedFaceTrace
#print axioms BernsteinObstacle.localFaceTrace_eq_of_commonFace
#print axioms BernsteinObstacle.clipped_localFaceTrace_eq_of_commonFace
#print axioms BernsteinObstacle.sharedBoundaryFaceTrace_eq_zero
#print axioms BernsteinObstacle.localBoundaryFaceTrace_eq_zero
#print axioms BernsteinObstacle.clippedRecovery_localBoundaryFaceTrace_eq_zero
#print axioms BernsteinObstacle.assemblyFeasibleSet_weaklySequentiallyClosed
#print axioms BernsteinObstacle.assemblyFeasibleSet_mosco_const
#print axioms BernsteinObstacle.assemblyFeasibleSet_identity_recovery
#print axioms BernsteinObstacle.assemblyMosco_recovery_closeness_implies_strongConvergence
#print axioms BernsteinObstacle.assembledClippedRecovery_implies_strongConvergence
#print axioms BernsteinObstacle.assemblyRecoveryOperator_closeness_implies_strongConvergence
#print axioms BernsteinObstacle.norm_sq_le_coefficientNormSq
#print axioms BernsteinObstacle.norm_le_sqrt_coefficientNormSq
#print axioms BernsteinObstacle.stronglyConverges_zero_of_coefficientNormSq_tendsto_zero
#print axioms BernsteinObstacle.stronglyConverges_of_recovery_coefficientNormSq
#print axioms BernsteinObstacle.stronglyConverges_of_recovery_coefficientNormSq_bound
#print axioms BernsteinObstacle.coefficientNormSq_sub_comm
#print axioms BernsteinObstacle.coefficientNormSq_tendsto_zero_of_scaled_le
#print axioms BernsteinObstacle.stronglyConverges_of_recovery_scaledEnergyGap
#print axioms BernsteinObstacle.assembledVISolutions_strongConvergence_of_energyGap
#print axioms BernsteinObstacle.assembledVISolutions_strongConvergence_of_clippedRecoveryEnergyGap
