import BernsteinObstacle

-- Focused final-five-percent recovery closure audit.

#check BernsteinObstacle.eventually_norm_lt_clearance
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.toAsymptoticData
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact

#print axioms BernsteinObstacle.eventually_norm_lt_clearance
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.toAsymptoticData
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
