import BernsteinObstacle

#check BernsteinObstacle.realRiskThickness
#check BernsteinObstacle.realVIExponent_eq_classification
#check BernsteinObstacle.realVIExponent_of_q_le_m
#check BernsteinObstacle.realVIExponent_of_m_le_q
#check BernsteinObstacle.realVIExponent_quadratic_codimOne
#check BernsteinObstacle.grandSharpRate_of_realMinkowskiComponents
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_realMinkowski
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_saturatedReal
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_realMinkowski
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_realMinkowski
#check BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_consistencyLimited

#print axioms BernsteinObstacle.realVIExponent_eq_classification
#print axioms BernsteinObstacle.realVIExponent_of_q_le_m
#print axioms BernsteinObstacle.realVIExponent_of_m_le_q
#print axioms BernsteinObstacle.realVIExponent_quadratic_codimOne
#print axioms BernsteinObstacle.grandSharpRate_of_realMinkowskiComponents
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_realMinkowski
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_saturatedReal
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_realMinkowski
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_realMinkowski
#print axioms BernsteinObstacle.ClearanceSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_consistencyLimited
