import BernsteinObstacle

#check BernsteinObstacle.simplexField_permute
#check BernsteinObstacle.simplexBasis_orientedLastFace_embed
#check BernsteinObstacle.simplexField_orientedLastFace_extension
#check BernsteinObstacle.simplexLatticePoint_orientedLastFaceMultiIndex
#check BernsteinObstacle.simplexSamplingCoefficients_nonneg
#check BernsteinObstacle.simplexSamplingRecovery_nonneg
#check BernsteinObstacle.simplexSamplingCoefficients_orientedLastFace
#check BernsteinObstacle.simplexSamplingCoefficients_orientedBoundary_eq_zero
#check BernsteinObstacle.orientedSimplexFaceTrace_eq_of_sharedDofs
#check BernsteinObstacle.clipped_orientedSimplexFaceTrace_eq_of_sharedDofs
#check BernsteinObstacle.orientedSimplexBoundaryFaceTrace_eq_zero
#check BernsteinObstacle.clipped_orientedSimplexBoundaryFaceTrace_eq_zero

#print axioms BernsteinObstacle.simplexField_permute
#print axioms BernsteinObstacle.simplexBasis_orientedLastFace_embed
#print axioms BernsteinObstacle.simplexField_orientedLastFace_extension
#print axioms BernsteinObstacle.simplexLatticePoint_orientedLastFaceMultiIndex
#print axioms BernsteinObstacle.simplexSamplingCoefficients_nonneg
#print axioms BernsteinObstacle.simplexSamplingRecovery_nonneg
#print axioms BernsteinObstacle.simplexSamplingCoefficients_orientedLastFace
#print axioms BernsteinObstacle.simplexSamplingCoefficients_orientedBoundary_eq_zero
#print axioms BernsteinObstacle.orientedSimplexFaceTrace_eq_of_sharedDofs
#print axioms BernsteinObstacle.clipped_orientedSimplexFaceTrace_eq_of_sharedDofs
#print axioms BernsteinObstacle.orientedSimplexBoundaryFaceTrace_eq_zero
#print axioms BernsteinObstacle.clipped_orientedSimplexBoundaryFaceTrace_eq_zero
