import BernsteinObstacle

#check BernsteinObstacle.moscoConverges_translated
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#check BernsteinObstacle.movingObstacleRecoveryRate
#check BernsteinObstacle.sharpRate_of_three_components
#check BernsteinObstacle.grandSharpRate_of_movingObstacle_components
#check BernsteinObstacle.grandSharpRate_exactObstacle_quadratic_codimOne
#check BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#check BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact

#print axioms BernsteinObstacle.moscoConverges_translated
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#print axioms BernsteinObstacle.movingObstacleRecoveryRate
#print axioms BernsteinObstacle.sharpRate_of_three_components
#print axioms BernsteinObstacle.grandSharpRate_of_movingObstacle_components
#print axioms BernsteinObstacle.grandSharpRate_exactObstacle_quadratic_codimOne
#print axioms BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#print axioms BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact
