import BernsteinObstacle

-- Canonical grand-theorem regression targets.

#check BernsteinObstacle.affineBox_mem_Icc
#check BernsteinObstacle.boxApprox_mem_Icc
#check BernsteinObstacle.simplexBoxApproxNat_mem_Icc
#check BernsteinObstacle.scheduledStage_tendsto_atTop
#check BernsteinObstacle.exists_scheduledDiagonalRecovery
#check BernsteinObstacle.mosco_of_scheduledRecovery_of_subset_closedConvex
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.scheduledRecovery
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.exists_threshold_of_eventually
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.exists_threshold
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.translatedSet
#check BernsteinObstacle.moscoConverges_translated
#check BernsteinObstacle.movingObstacleCone
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.BilateralBarrierEnvelopeData.moscoConverges
#check BernsteinObstacle.BilateralBarrierEnvelopeData.inner_and_mosco
#check BernsteinObstacle.hilbert_vi_pythagorean
#check BernsteinObstacle.hilbert_vi_unique
#check BernsteinObstacle.nested_hilbert_vi_recovery_error_sq
#check BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#check BernsteinObstacle.BilateralBarrierEnvelopeData.grandBarrier_mosco_and_hilbertConvergence
#check BernsteinObstacle.SobolevFEMRecoveryData.toBarrierEnvelopeData
#check BernsteinObstacle.SobolevFEMRecoveryData.barrierEnvelope_moscoConverges
#check BernsteinObstacle.SobolevFEMRecoveryData.grandBarrier_hilbertConvergence
#check BernsteinObstacle.twoScaleRate_of_energy_components
#check BernsteinObstacle.universalFirstOrderRate_of_recovery_and_measure
#check BernsteinObstacle.monotoneInnerCone_falk_sq
#check BernsteinObstacle.IsOperatorVISolution
#check BernsteinObstacle.monotoneInnerCone_operator_core
#check BernsteinObstacle.monotoneInnerCone_operator_falk_sq
#check BernsteinObstacle.vanishingCodimensionScale_sq
#check BernsteinObstacle.strip_sum_energy_le_vanishingCodimension
#check BernsteinObstacle.repair_norm_le_vanishingCodimension_of_element_bounds
#check BernsteinObstacle.sharpRate_of_vanishingCodimension_components
#check BernsteinObstacle.consistencyLimitedOrder_eq_vanishingOrder
#check BernsteinObstacle.quadraticContact_codimOne_saturation
#check BernsteinObstacle.phaseLockedQuadraticMiddleCoefficient_neg
#check BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity
#check BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity_eq_scale_sq
#check BernsteinObstacle.phaseLockedQuadraticSlopeEnergy_lowerBound
#check BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#check BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
#check BernsteinObstacle.threeHalvesContactLaw
#check BernsteinObstacle.balancedContactOrder_equalizes

#print axioms BernsteinObstacle.affineBox_mem_Icc
#print axioms BernsteinObstacle.boxApprox_mem_Icc
#print axioms BernsteinObstacle.simplexBoxApproxNat_mem_Icc
#print axioms BernsteinObstacle.scheduledStage_tendsto_atTop
#print axioms BernsteinObstacle.exists_scheduledDiagonalRecovery
#print axioms BernsteinObstacle.mosco_of_scheduledRecovery_of_subset_closedConvex
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.scheduledRecovery
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.exists_threshold_of_eventually
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.exists_threshold
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.translatedSet
#print axioms BernsteinObstacle.moscoConverges_translated
#print axioms BernsteinObstacle.movingObstacleCone
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.BilateralBarrierEnvelopeData.moscoConverges
#print axioms BernsteinObstacle.BilateralBarrierEnvelopeData.inner_and_mosco
#print axioms BernsteinObstacle.hilbert_vi_pythagorean
#print axioms BernsteinObstacle.hilbert_vi_unique
#print axioms BernsteinObstacle.nested_hilbert_vi_recovery_error_sq
#print axioms BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#print axioms BernsteinObstacle.BilateralBarrierEnvelopeData.grandBarrier_mosco_and_hilbertConvergence
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.toBarrierEnvelopeData
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.barrierEnvelope_moscoConverges
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.grandBarrier_hilbertConvergence
#print axioms BernsteinObstacle.twoScaleRate_of_energy_components
#print axioms BernsteinObstacle.universalFirstOrderRate_of_recovery_and_measure
#print axioms BernsteinObstacle.monotoneInnerCone_falk_sq
#print axioms BernsteinObstacle.IsOperatorVISolution
#print axioms BernsteinObstacle.monotoneInnerCone_operator_core
#print axioms BernsteinObstacle.monotoneInnerCone_operator_falk_sq
#print axioms BernsteinObstacle.vanishingCodimensionScale_sq
#print axioms BernsteinObstacle.strip_sum_energy_le_vanishingCodimension
#print axioms BernsteinObstacle.repair_norm_le_vanishingCodimension_of_element_bounds
#print axioms BernsteinObstacle.sharpRate_of_vanishingCodimension_components
#print axioms BernsteinObstacle.consistencyLimitedOrder_eq_vanishingOrder
#print axioms BernsteinObstacle.quadraticContact_codimOne_saturation
#print axioms BernsteinObstacle.phaseLockedQuadraticMiddleCoefficient_neg
#print axioms BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity
#print axioms BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity_eq_scale_sq
#print axioms BernsteinObstacle.phaseLockedQuadraticSlopeEnergy_lowerBound
#print axioms BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#print axioms BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.AsymptoticSobolevFEMRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
#print axioms BernsteinObstacle.threeHalvesContactLaw
#print axioms BernsteinObstacle.balancedContactOrder_equalizes
