import BernsteinObstacle

#check BernsteinObstacle.moscoConverges_translated
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#check BernsteinObstacle.movingObstacleRecoveryRate
#check BernsteinObstacle.sharpRate_of_three_components
#check BernsteinObstacle.grandSharpRate_of_movingObstacle_components
#check BernsteinObstacle.grandSharpRate_exactObstacle_quadratic_codimOne
#check BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#check BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact
#check BernsteinObstacle.phaseLockedQuadraticSlopeEnergyDensity_expand
#check BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity
#check BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity_eq_scale_sq
#check BernsteinObstacle.phaseLockedQuadraticSlopeEnergy_lowerBound
#check BernsteinObstacle.simplexFieldNat_contact_mem_Icc_of_modulus
#check BernsteinObstacle.sum_weighted_contact_recovery_le
#check BernsteinObstacle.universalRate_of_modulusIndicator_and_contact
#check BernsteinObstacle.simplexBoxApproxNat_mem_Icc

#print axioms BernsteinObstacle.moscoConverges_translated
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#print axioms BernsteinObstacle.movingObstacleRecoveryRate
#print axioms BernsteinObstacle.sharpRate_of_three_components
#print axioms BernsteinObstacle.grandSharpRate_of_movingObstacle_components
#print axioms BernsteinObstacle.grandSharpRate_exactObstacle_quadratic_codimOne
#print axioms BernsteinObstacle.grandSharpRate_of_consistencyLimitedComponents
#print axioms BernsteinObstacle.grandSharpRate_quadraticContact_saturation
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_quadraticContact
#print axioms BernsteinObstacle.phaseLockedQuadraticSlopeEnergyDensity_expand
#print axioms BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity
#print axioms BernsteinObstacle.intervalIntegral_phaseLockedQuadraticSlopeEnergyDensity_eq_scale_sq
#print axioms BernsteinObstacle.phaseLockedQuadraticSlopeEnergy_lowerBound
#print axioms BernsteinObstacle.simplexFieldNat_contact_mem_Icc_of_modulus
#print axioms BernsteinObstacle.sum_weighted_contact_recovery_le
#print axioms BernsteinObstacle.universalRate_of_modulusIndicator_and_contact
#print axioms BernsteinObstacle.simplexBoxApproxNat_mem_Icc
