import BernsteinObstacle

#check BernsteinObstacle.IsHilbertVISolution
#check BernsteinObstacle.hilbert_vi_pythagorean
#check BernsteinObstacle.hilbert_vi_unique
#check BernsteinObstacle.nested_hilbert_vi_recovery_error_sq
#check BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.hilbertVISolutions_strongConvergence
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.mosco_and_hilbertVISolutions_strongConvergence

#print axioms BernsteinObstacle.hilbert_vi_pythagorean
#print axioms BernsteinObstacle.hilbert_vi_unique
#print axioms BernsteinObstacle.nested_hilbert_vi_recovery_error_sq
#print axioms BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.hilbertVISolutions_strongConvergence
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.mosco_and_hilbertVISolutions_strongConvergence
