import BernsteinObstacle.FlatInterfaceBenchmark
import BernsteinObstacle.GenericShiftAveraging
import BernsteinObstacle.DesignedTubularMesh
import BernsteinObstacle.AlignedMeshObstruction
import BernsteinObstacle.PhaseWeightedSaturation

#print axioms BernsteinObstacle.flatLeftPrism_subset_upperCutTriangle
#print axioms BernsteinObstacle.flatRightPrism_subset_lowerCutTriangle
#print axioms BernsteinObstacle.flatComparison_contact_energy
#print axioms BernsteinObstacle.flatComparison_noncontact_energy
#print axioms BernsteinObstacle.flatComparison_multiplier_term
#print axioms BernsteinObstacle.flatBenchmark_sharp_sandwich
#print axioms BernsteinObstacle.goodTranslationSet_measure_lowerBound
#print axioms BernsteinObstacle.retainedCount_of_goodTranslation
#print axioms BernsteinObstacle.tubularJacobian_bounds
#print axioms BernsteinObstacle.curvedFiber_phase_bounds
#print axioms BernsteinObstacle.curvedElement_remainderEnergy_bound
#print axioms BernsteinObstacle.exactRepresentability_refutes_positiveLowerBound
#print axioms BernsteinObstacle.quadraticContactPhaseCoefficient_tendsto_zero
#print axioms BernsteinObstacle.phaseWeighted_error_ge_threeHalves_of_sum_le_sq
