import BernsteinObstacle

#check BernsteinObstacle.vanishingCodimensionScale_nonneg
#check BernsteinObstacle.vanishingCodimensionScale_sq
#check BernsteinObstacle.vanishingCodimension_power_cancellation
#check BernsteinObstacle.strip_sum_energy_le_vanishingCodimension
#check BernsteinObstacle.repair_norm_le_vanishingCodimension
#check BernsteinObstacle.repair_norm_le_vanishingCodimension_of_element_bounds
#check BernsteinObstacle.vanishingCodimensionScale_quadratic_codimOne
#check BernsteinObstacle.sharpRate_of_vanishingCodimension_components

#print axioms BernsteinObstacle.vanishingCodimensionScale_nonneg
#print axioms BernsteinObstacle.vanishingCodimensionScale_sq
#print axioms BernsteinObstacle.vanishingCodimension_power_cancellation
#print axioms BernsteinObstacle.strip_sum_energy_le_vanishingCodimension
#print axioms BernsteinObstacle.repair_norm_le_vanishingCodimension
#print axioms BernsteinObstacle.repair_norm_le_vanishingCodimension_of_element_bounds
#print axioms BernsteinObstacle.vanishingCodimensionScale_quadratic_codimOne
#print axioms BernsteinObstacle.sharpRate_of_vanishingCodimension_components
