import BernsteinObstacle

#check BernsteinObstacle.weaklySequentiallyClosed_of_convex_isClosed
#check BernsteinObstacle.mosco_of_recovery_of_subset_of_closedConvex
#check BernsteinObstacle.mosco_of_recovery_operators_of_subset_of_closedConvex
#check BernsteinObstacle.stronglyConverges_comp_tendsto_atTop
#check BernsteinObstacle.diagonalRecovery_stronglyConverges
#check BernsteinObstacle.mosco_of_diagonalRecovery_of_subset_closedConvex
#check BernsteinObstacle.diagonalRecovery_minimizers_strongConvergence
#check BernsteinObstacle.scheduledStage_tendsto_atTop
#check BernsteinObstacle.scheduledError_tendsto_zero
#check BernsteinObstacle.exists_scheduledDiagonalRecovery
#check BernsteinObstacle.mosco_of_scheduledRecovery_of_subset_closedConvex
#check BernsteinObstacle.SobolevFEMRecoveryData.diagonalRecovery
#check BernsteinObstacle.SobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.SobolevFEMRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.scheduledRecovery
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.stronglyConverges_add
#check BernsteinObstacle.weaklyConverges_sub_stronglyConverges
#check BernsteinObstacle.moscoConverges_translated
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#check BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#check BernsteinObstacle.movingClosedConvexRecovery_strongConvergence
#check BernsteinObstacle.movingClosedConvexRecoverySequence_strongConvergence

#print axioms BernsteinObstacle.weaklySequentiallyClosed_of_convex_isClosed
#print axioms BernsteinObstacle.mosco_of_recovery_of_subset_of_closedConvex
#print axioms BernsteinObstacle.mosco_of_recovery_operators_of_subset_of_closedConvex
#print axioms BernsteinObstacle.stronglyConverges_comp_tendsto_atTop
#print axioms BernsteinObstacle.diagonalRecovery_stronglyConverges
#print axioms BernsteinObstacle.mosco_of_diagonalRecovery_of_subset_closedConvex
#print axioms BernsteinObstacle.diagonalRecovery_minimizers_strongConvergence
#print axioms BernsteinObstacle.scheduledStage_tendsto_atTop
#print axioms BernsteinObstacle.scheduledError_tendsto_zero
#print axioms BernsteinObstacle.exists_scheduledDiagonalRecovery
#print axioms BernsteinObstacle.mosco_of_scheduledRecovery_of_subset_closedConvex
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.diagonalRecovery
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.scheduledRecovery
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.stronglyConverges_add
#print axioms BernsteinObstacle.weaklyConverges_sub_stronglyConverges
#print axioms BernsteinObstacle.moscoConverges_translated
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.movingObstacle_minimizers_strongConvergence
#print axioms BernsteinObstacle.ThresholdSobolevFEMRecoveryData.fixedObstacle_moscoConverges
#print axioms BernsteinObstacle.movingClosedConvexRecovery_strongConvergence
#print axioms BernsteinObstacle.movingClosedConvexRecoverySequence_strongConvergence
