import BernsteinObstacle

#check BernsteinObstacle.weaklySequentiallyClosed_of_convex_isClosed
#check BernsteinObstacle.mosco_of_recovery_of_subset_of_closedConvex
#check BernsteinObstacle.mosco_of_recovery_operators_of_subset_of_closedConvex
#check BernsteinObstacle.stronglyConverges_comp_tendsto_atTop
#check BernsteinObstacle.diagonalRecovery_stronglyConverges
#check BernsteinObstacle.mosco_of_diagonalRecovery_of_subset_closedConvex
#check BernsteinObstacle.diagonalRecovery_minimizers_strongConvergence
#check BernsteinObstacle.SobolevFEMRecoveryData.diagonalRecovery
#check BernsteinObstacle.SobolevFEMRecoveryData.moscoConverges
#check BernsteinObstacle.SobolevFEMRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.movingClosedConvexRecovery_strongConvergence
#check BernsteinObstacle.movingClosedConvexRecoverySequence_strongConvergence

#print axioms BernsteinObstacle.weaklySequentiallyClosed_of_convex_isClosed
#print axioms BernsteinObstacle.mosco_of_recovery_of_subset_of_closedConvex
#print axioms BernsteinObstacle.mosco_of_recovery_operators_of_subset_of_closedConvex
#print axioms BernsteinObstacle.stronglyConverges_comp_tendsto_atTop
#print axioms BernsteinObstacle.diagonalRecovery_stronglyConverges
#print axioms BernsteinObstacle.mosco_of_diagonalRecovery_of_subset_closedConvex
#print axioms BernsteinObstacle.diagonalRecovery_minimizers_strongConvergence
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.diagonalRecovery
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.moscoConverges
#print axioms BernsteinObstacle.SobolevFEMRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.movingClosedConvexRecovery_strongConvergence
#print axioms BernsteinObstacle.movingClosedConvexRecoverySequence_strongConvergence
