import BernsteinObstacle

-- Terminal axiom audit for the operator-valued V6 bridge.
#print axioms BernsteinObstacle.operator_vi_residual_nonneg
#print axioms BernsteinObstacle.operator_vi_reverse_direction_nonpos
#print axioms BernsteinObstacle.operator_vi_innerCone_falk
#print axioms BernsteinObstacle.operator_vi_error_sq_scaled
#print axioms BernsteinObstacle.operator_vi_rate_compose_scaled
#print axioms BernsteinObstacle.operator_vi_sameCone_perturbation_scaled
