import BernsteinObstacle.InterfaceCoverCount
import BernsteinObstacle.PhysicalSaturationComposition

#check BernsteinObstacle.sum_le_card_mul_of_le
#check BernsteinObstacle.interfaceCover_card_lowerBound
#check BernsteinObstacle.cutPatch_error_ge_threeHalves_of_interfaceCover
#check BernsteinObstacle.mappedQuadraticHingeLocalConstant_nonneg
#check BernsteinObstacle.physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#check BernsteinObstacle.physicalMappedQuadraticHinge_threeHalvesLowerBound

#print axioms BernsteinObstacle.sum_le_card_mul_of_le
#print axioms BernsteinObstacle.interfaceCover_card_lowerBound
#print axioms BernsteinObstacle.cutPatch_error_ge_threeHalves_of_interfaceCover
#print axioms BernsteinObstacle.mappedQuadraticHingeLocalConstant_nonneg
#print axioms BernsteinObstacle.physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#print axioms BernsteinObstacle.physicalMappedQuadraticHinge_threeHalvesLowerBound
