import BernsteinObstacle.InterfaceCoverCount
import BernsteinObstacle.RemainderElementEnergy
import BernsteinObstacle.RemainderPatchScaling
import BernsteinObstacle.PhysicalSaturationComposition
import BernsteinObstacle.NormedPhysicalSaturation

#check BernsteinObstacle.interface_sum_le_card_mul_of_le
#check BernsteinObstacle.interfaceCover_card_lowerBound
#check BernsteinObstacle.cutPatch_error_ge_threeHalves_of_interfaceCover
#check BernsteinObstacle.integral_le_realMass_mul_of_ae_le
#check BernsteinObstacle.remainderElement_energy_le_higherOrder
#check BernsteinObstacle.remainderPatch_sum_energy_le_higherOrder
#check BernsteinObstacle.remainderPatch_error_le_higherOrder
#check BernsteinObstacle.physicalLowerBound_of_remainderPatchScaling
#check BernsteinObstacle.mappedQuadraticHingeLocalConstant_nonneg
#check BernsteinObstacle.mappedQuadraticHingeLocalConstant_pos
#check BernsteinObstacle.mappedQuadraticHingeLeadingCoefficient_pos
#check BernsteinObstacle.physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#check BernsteinObstacle.physicalMappedQuadraticHinge_threeHalvesLowerBound
#check BernsteinObstacle.norm_physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#check BernsteinObstacle.norm_physicalMappedQuadraticHinge_threeHalvesLowerBound

#print axioms BernsteinObstacle.interface_sum_le_card_mul_of_le
#print axioms BernsteinObstacle.interfaceCover_card_lowerBound
#print axioms BernsteinObstacle.cutPatch_error_ge_threeHalves_of_interfaceCover
#print axioms BernsteinObstacle.integral_le_realMass_mul_of_ae_le
#print axioms BernsteinObstacle.remainderElement_energy_le_higherOrder
#print axioms BernsteinObstacle.remainderPatch_sum_energy_le_higherOrder
#print axioms BernsteinObstacle.remainderPatch_error_le_higherOrder
#print axioms BernsteinObstacle.physicalLowerBound_of_remainderPatchScaling
#print axioms BernsteinObstacle.mappedQuadraticHingeLocalConstant_nonneg
#print axioms BernsteinObstacle.mappedQuadraticHingeLocalConstant_pos
#print axioms BernsteinObstacle.mappedQuadraticHingeLeadingCoefficient_pos
#print axioms BernsteinObstacle.physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#print axioms BernsteinObstacle.physicalMappedQuadraticHinge_threeHalvesLowerBound
#print axioms BernsteinObstacle.norm_physicalCutPatch_threeHalvesLowerBound_of_interfaceCover_and_remainder
#print axioms BernsteinObstacle.norm_physicalMappedQuadraticHinge_threeHalvesLowerBound
