import BernsteinObstacle.QuadraticHingeProjection
import BernsteinObstacle.QuadraticHingeBestApproximation

#check BernsteinObstacle.intervalIntegral_quadraticPolynomial
#check BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_identity
#check BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_at_optimal
#check BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_lowerBound
#check BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_uniformLowerBound
#check BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_isGLB
#check BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_identity
#check BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_at_optimal
#check BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_lowerBound
#check BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_uniformLowerBound
#check BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_isGLB
#check BernsteinObstacle.scaledQuadraticHinge_fullSpace_threeHalvesLowerBound

#print axioms BernsteinObstacle.intervalIntegral_quadraticPolynomial
#print axioms BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_identity
#print axioms BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_at_optimal
#print axioms BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_lowerBound
#print axioms BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_uniformLowerBound
#print axioms BernsteinObstacle.quadraticHingeAffineDerivativeErrorSq_isGLB
#print axioms BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_identity
#print axioms BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_at_optimal
#print axioms BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_lowerBound
#print axioms BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_uniformLowerBound
#print axioms BernsteinObstacle.scaledQuadraticHingeAffineDerivativeErrorSq_isGLB
#print axioms BernsteinObstacle.scaledQuadraticHinge_fullSpace_threeHalvesLowerBound
