import BernsteinObstacle

#check BernsteinObstacle.grandSharpRate_of_realMinkowskiComponents
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_realMinkowski
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#check BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_saturatedReal

#print axioms BernsteinObstacle.grandSharpRate_of_realMinkowskiComponents
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_realMinkowski
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_consistencyLimited
#print axioms BernsteinObstacle.bernsteinBezierObstacleGrandTheorem_saturatedReal
