import BernsteinObstacle

#check BernsteinObstacle.nested_hilbert_vi_error_sq_tendsto_zero_of_recovery
#check BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#check BernsteinObstacle.codimOne_patch_gradient_sq_le_cubic
#check BernsteinObstacle.cubic_squared_cost_tendsto_zero
#check BernsteinObstacle.combined_bulk_strip_rate_tendsto_zero

#print axioms BernsteinObstacle.nested_hilbert_vi_error_sq_tendsto_zero_of_recovery
#print axioms BernsteinObstacle.nested_hilbert_vi_strongConvergence_of_recovery
#print axioms BernsteinObstacle.codimOne_patch_gradient_sq_le_cubic
#print axioms BernsteinObstacle.cubic_squared_cost_tendsto_zero
#print axioms BernsteinObstacle.combined_bulk_strip_rate_tendsto_zero
