import BernsteinObstacle.RemainderAbsorption

#check BernsteinObstacle.threeHalvesLowerBound_stable_under_higherOrderRemainder
#check BernsteinObstacle.threeHalvesLowerBound_stable_with_fraction
#check BernsteinObstacle.freeBoundary_error_ge_half_threeHalves_of_model_remainder

#print axioms BernsteinObstacle.threeHalvesLowerBound_stable_under_higherOrderRemainder
#print axioms BernsteinObstacle.threeHalvesLowerBound_stable_with_fraction
#print axioms BernsteinObstacle.freeBoundary_error_ge_half_threeHalves_of_model_remainder
