import BernsteinObstacle

#check BernsteinObstacle.coefficient_nonneg_of_abs_sub_le
#check BernsteinObstacle.value_lt_error_of_coefficient_neg
#check BernsteinObstacle.abs_coefficient_le_quadratic_scale
#check BernsteinObstacle.stableInverse_quadratic_norm_bound
#check BernsteinObstacle.coefficient_nonneg_of_quadratic_growth_and_local_distance
#check BernsteinObstacle.local_distance_lt_of_coefficient_neg
#check BernsteinObstacle.abs_coefficient_le_quadratic_on_local_strip
#check BernsteinObstacle.quadratic_error_le_linear_growth
#check BernsteinObstacle.boundary_offFace_coefficient_nonneg
#check BernsteinObstacle.boundary_errorConstant_mul_h_gt_of_coefficient_neg
#check BernsteinObstacle.strip_power_cancellation
#check BernsteinObstacle.threeHalvesScale_sq
#check BernsteinObstacle.sqrt_cubic_eq_threeHalvesScale
#check BernsteinObstacle.sharpRate_of_energy_components
#check BernsteinObstacle.strip_sum_energy_le_cubic
#check BernsteinObstacle.repair_norm_le_threeHalves_of_element_bounds
#check BernsteinObstacle.feasibleRecoveryRate_of_interpolation_and_repair
#check BernsteinObstacle.sharpMinimizerRate_of_recovery_and_multiplier
#check BernsteinObstacle.correctedSharpMinimizerRate_of_local_strip
#check BernsteinObstacle.corrected_localization_and_sharp_rate
#check BernsteinObstacle.broken_bulk_sum_le_rate
#check BernsteinObstacle.multiplier_strip_le_cubic
#check BernsteinObstacle.correctedSharpMinimizerRate_of_broken_bulk_and_multiplier
#check BernsteinObstacle.optimalBulkRate_of_balanced_interface
#check BernsteinObstacle.optimalBulkRate_of_exact_balance

#print axioms BernsteinObstacle.coefficient_nonneg_of_abs_sub_le
#print axioms BernsteinObstacle.value_lt_error_of_coefficient_neg
#print axioms BernsteinObstacle.abs_coefficient_le_quadratic_scale
#print axioms BernsteinObstacle.stableInverse_quadratic_norm_bound
#print axioms BernsteinObstacle.coefficient_nonneg_of_quadratic_growth_and_local_distance
#print axioms BernsteinObstacle.local_distance_lt_of_coefficient_neg
#print axioms BernsteinObstacle.abs_coefficient_le_quadratic_on_local_strip
#print axioms BernsteinObstacle.quadratic_error_le_linear_growth
#print axioms BernsteinObstacle.boundary_offFace_coefficient_nonneg
#print axioms BernsteinObstacle.boundary_errorConstant_mul_h_gt_of_coefficient_neg
#print axioms BernsteinObstacle.strip_power_cancellation
#print axioms BernsteinObstacle.threeHalvesScale_sq
#print axioms BernsteinObstacle.sqrt_cubic_eq_threeHalvesScale
#print axioms BernsteinObstacle.sharpRate_of_energy_components
#print axioms BernsteinObstacle.strip_sum_energy_le_cubic
#print axioms BernsteinObstacle.repair_norm_le_threeHalves_of_element_bounds
#print axioms BernsteinObstacle.feasibleRecoveryRate_of_interpolation_and_repair
#print axioms BernsteinObstacle.sharpMinimizerRate_of_recovery_and_multiplier
#print axioms BernsteinObstacle.correctedSharpMinimizerRate_of_local_strip
#print axioms BernsteinObstacle.corrected_localization_and_sharp_rate
#print axioms BernsteinObstacle.broken_bulk_sum_le_rate
#print axioms BernsteinObstacle.multiplier_strip_le_cubic
#print axioms BernsteinObstacle.correctedSharpMinimizerRate_of_broken_bulk_and_multiplier
#print axioms BernsteinObstacle.optimalBulkRate_of_balanced_interface
#print axioms BernsteinObstacle.optimalBulkRate_of_exact_balance
