import BernsteinObstacle

#check BernsteinObstacle.coefficient_nonneg_of_abs_sub_le
#check BernsteinObstacle.value_lt_error_of_coefficient_neg
#check BernsteinObstacle.abs_coefficient_le_quadratic_scale
#check BernsteinObstacle.stableInverse_quadratic_norm_bound
#check BernsteinObstacle.strip_power_cancellation
#check BernsteinObstacle.threeHalvesScale_sq
#check BernsteinObstacle.sqrt_cubic_eq_threeHalvesScale
#check BernsteinObstacle.sharpRate_of_energy_components
#check BernsteinObstacle.strip_sum_energy_le_cubic
#check BernsteinObstacle.repair_norm_le_threeHalves_of_element_bounds
#check BernsteinObstacle.feasibleRecoveryRate_of_interpolation_and_repair
#check BernsteinObstacle.sharpMinimizerRate_of_recovery_and_multiplier
#check BernsteinObstacle.affineBox_mem_Icc
#check BernsteinObstacle.boxApprox_mem_Icc
#check BernsteinObstacle.twoScaleRate_of_energy_components
#check BernsteinObstacle.universalFirstOrderRate_of_energy
#check BernsteinObstacle.universalFirstOrderRate_of_recovery_and_measure

#print axioms BernsteinObstacle.coefficient_nonneg_of_abs_sub_le
#print axioms BernsteinObstacle.value_lt_error_of_coefficient_neg
#print axioms BernsteinObstacle.abs_coefficient_le_quadratic_scale
#print axioms BernsteinObstacle.stableInverse_quadratic_norm_bound
#print axioms BernsteinObstacle.strip_power_cancellation
#print axioms BernsteinObstacle.threeHalvesScale_sq
#print axioms BernsteinObstacle.sqrt_cubic_eq_threeHalvesScale
#print axioms BernsteinObstacle.sharpRate_of_energy_components
#print axioms BernsteinObstacle.strip_sum_energy_le_cubic
#print axioms BernsteinObstacle.repair_norm_le_threeHalves_of_element_bounds
#print axioms BernsteinObstacle.feasibleRecoveryRate_of_interpolation_and_repair
#print axioms BernsteinObstacle.sharpMinimizerRate_of_recovery_and_multiplier
#print axioms BernsteinObstacle.affineBox_mem_Icc
#print axioms BernsteinObstacle.boxApprox_mem_Icc
#print axioms BernsteinObstacle.twoScaleRate_of_energy_components
#print axioms BernsteinObstacle.universalFirstOrderRate_of_energy
#print axioms BernsteinObstacle.universalFirstOrderRate_of_recovery_and_measure
