import BernsteinObstacle

#check BernsteinObstacle.fullSimplexExponent_apply
#check BernsteinObstacle.prod_X_pow_eq_fullSimplexMonomial
#check BernsteinObstacle.eval_fullSimplexMonomial
#check BernsteinObstacle.simplexMultinomialPolynomialExpansion
#check BernsteinObstacle.pderiv_sum_X_eq_one
#check BernsteinObstacle.pderiv_sum_X_pow
#check BernsteinObstacle.X_mul_pderiv_simplexMultinomialExpansion
#check BernsteinObstacle.simplexBasisNat_firstMoment_unnormalized

#print axioms BernsteinObstacle.fullSimplexExponent_apply
#print axioms BernsteinObstacle.prod_X_pow_eq_fullSimplexMonomial
#print axioms BernsteinObstacle.eval_fullSimplexMonomial
#print axioms BernsteinObstacle.simplexMultinomialPolynomialExpansion
#print axioms BernsteinObstacle.pderiv_sum_X_eq_one
#print axioms BernsteinObstacle.pderiv_sum_X_pow
#print axioms BernsteinObstacle.X_mul_pderiv_simplexMultinomialExpansion
#print axioms BernsteinObstacle.simplexBasisNat_firstMoment_unnormalized
