import BernsteinObstacle

-- Minimal current-stack Sobolev port.
#check BernsteinObstacle.SobolevH01Port.HasWeakPartialDeriv
#check BernsteinObstacle.SobolevH01Port.HasWeakGrad
#check BernsteinObstacle.SobolevH01Port.MemW1p
#check BernsteinObstacle.SobolevH01Port.MemW1pWitness
#check BernsteinObstacle.SobolevH01Port.MemW01p
#check BernsteinObstacle.SobolevH01Port.MemH01
#check BernsteinObstacle.SobolevH01Port.smoothApproxData_of_memH01
#check BernsteinObstacle.SobolevH01Port.positivePart
#check BernsteinObstacle.SobolevH01Port.positivePartGrad
#check BernsteinObstacle.SobolevH01Port.indicator_component_memLp
#check BernsteinObstacle.SobolevH01Port.positivePartGrad_component_memLp
#check BernsteinObstacle.SobolevH01Port.NonnegativeH01ApproximationWitness.memH01

-- Actual assembled shared-DOF recovery and terminal theorem.
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.recovery_mem_of_norm_lt_clearance
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.toClearanceData
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.moscoConverges
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.minimizers_strongConvergence
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.movingObstacle_moscoConverges
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.bernsteinBezierObstacleGrandTheorem
#check BernsteinObstacle.AssembledFreeCoefficientRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact

#print axioms BernsteinObstacle.SobolevH01Port.MemW1pWitness.memW1p
#print axioms BernsteinObstacle.SobolevH01Port.smoothApproxData_of_memH01
#print axioms BernsteinObstacle.SobolevH01Port.positivePart_nonneg
#print axioms BernsteinObstacle.SobolevH01Port.positivePart_eq_self
#print axioms BernsteinObstacle.SobolevH01Port.positivePart_eq_zero
#print axioms BernsteinObstacle.SobolevH01Port.indicator_component_memLp
#print axioms BernsteinObstacle.SobolevH01Port.positivePartGrad_component_memLp
#print axioms BernsteinObstacle.SobolevH01Port.NonnegativeH01ApproximationWitness.memH01
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.recovery_mem_of_norm_lt_clearance
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.toClearanceData
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.moscoConverges
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.minimizers_strongConvergence
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.movingObstacle_moscoConverges
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.bernsteinBezierObstacleGrandTheorem
#print axioms BernsteinObstacle.AssembledFreeCoefficientRecoveryData.bernsteinBezierObstacleGrandTheorem_quadraticContact
