import BernsteinObstacle.QuadraticLineRestriction
import BernsteinObstacle.TransversePrismSaturation
import BernsteinObstacle.ReferencePrismSaturation

#check BernsteinObstacle.QuadraticPolynomialData.eval_affineLine
#check BernsteinObstacle.hasDerivAt_quadraticPolynomial
#check BernsteinObstacle.QuadraticPolynomialData.hasDerivAt_eval_affineLine
#check BernsteinObstacle.QuadraticPolynomialData.lineDerivative_eq_affine
#check BernsteinObstacle.QuadraticPolynomialData.lineDerivative_explicit
#check BernsteinObstacle.transversePrism_fiberIntegral_lowerBound
#check BernsteinObstacle.transversePrism_localEnergy_lowerBound
#check BernsteinObstacle.transversePrism_quadraticPolynomial_localEnergy_lowerBound
#check BernsteinObstacle.referencePrism_exactEnergy_lowerBound
#check BernsteinObstacle.referencePrism_quadraticPolynomial_exactEnergy_lowerBound

#print axioms BernsteinObstacle.QuadraticPolynomialData.eval_affineLine
#print axioms BernsteinObstacle.hasDerivAt_quadraticPolynomial
#print axioms BernsteinObstacle.QuadraticPolynomialData.hasDerivAt_eval_affineLine
#print axioms BernsteinObstacle.QuadraticPolynomialData.lineDerivative_eq_affine
#print axioms BernsteinObstacle.QuadraticPolynomialData.lineDerivative_explicit
#print axioms BernsteinObstacle.transversePrism_fiberIntegral_lowerBound
#print axioms BernsteinObstacle.transversePrism_localEnergy_lowerBound
#print axioms BernsteinObstacle.transversePrism_quadraticPolynomial_localEnergy_lowerBound
#print axioms BernsteinObstacle.referencePrism_exactEnergy_lowerBound
#print axioms BernsteinObstacle.referencePrism_quadraticPolynomial_exactEnergy_lowerBound
