import BernsteinObstacle.LowerStripSaturation

#check BernsteinObstacle.transversePrism_fiberIntegral_lowerBound
#check BernsteinObstacle.transversePrism_localEnergy_lowerBound
#check BernsteinObstacle.card_mul_le_sum_of_le
#check BernsteinObstacle.strip_sum_energy_ge_cubic
#check BernsteinObstacle.threeHalves_lowerBound_of_cubic_le_sq
#check BernsteinObstacle.fullSpace_error_ge_threeHalves_of_element_lowerBounds

#print axioms BernsteinObstacle.transversePrism_fiberIntegral_lowerBound
#print axioms BernsteinObstacle.transversePrism_localEnergy_lowerBound
#print axioms BernsteinObstacle.card_mul_le_sum_of_le
#print axioms BernsteinObstacle.strip_sum_energy_ge_cubic
#print axioms BernsteinObstacle.threeHalves_lowerBound_of_cubic_le_sq
#print axioms BernsteinObstacle.fullSpace_error_ge_threeHalves_of_element_lowerBounds
