name = "wowii314_audit"
defaultTargets = []

[[require]]
name = "formal_conjectures"
git = "https://github.com/DomTheDeveloper/formal-conjectures.git"
rev = "5c5bd13501f577bbb528d1ccef9c61a338c796f4"
