name = "wowii314_audit"
defaultTargets = []

[[require]]
name = "formal_conjectures"
git = "https://github.com/DomTheDeveloper/formal-conjectures.git"
rev = "1967d975cc0c31fb0405a53930165e4f8e533c43"
