import BernsteinObstacle.FlatInterfaceBenchmark
import BernsteinObstacle.GenericShiftAveraging
import BernsteinObstacle.DesignedTubularMesh
import BernsteinObstacle.AlignedMeshObstruction
import BernsteinObstacle.PhaseWeightedSaturation
import BernsteinObstacle.MeshTheoremCompositions
