import BernsteinObstacle.GlobalSmoothSaturation
import Mathlib.Analysis.SpecificLimits.Basic
import Mathlib.Tactic

open Filter Topology

namespace BernsteinObstacle

noncomputable section

/-!
# Green-profile asymptotic bridge

The exact one-dimensional asymptotic constant has two logically distinct
parts.  First, a Hilbert-space trace constraint has an exact minimum determined
by the norm of the trace functional.  Second, eventual lower and upper bounds
with a vanishing gap force convergence of the normalized discrete errors.

The concrete Sobolev application supplies the trace representer and proves that
the rescaled Bernstein coefficient converges to point evaluation.
-/

section LinearConstraint

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]

/-- Closed half-space generated by a continuous linear functional. -/
def linearConstraintSet (T : E →L[ℝ] ℝ) (gamma : ℝ) : Set E :=
  {w | gamma ≤ T w}

/-- Exact norm minimization for a linear constraint when a norm-attaining
representer is supplied.

In the Sobolev application, `T` is point evaluation at the contact point,
`g` is its Riesz representer, and `tau = ‖T‖`. -/
theorem halfspace_bestApproximationError_eq
    (T : E →L[ℝ] ℝ) (g : E) (gamma tau : ℝ)
    (hgamma : 0 ≤ gamma) (htau : 0 < tau)
    (hTnorm : ‖T‖ = tau)
    (hTg : T g = tau ^ 2)
    (hgnorm : ‖g‖ = tau) :
    bestApproximationError (0 : E) (linearConstraintSet T gamma) = gamma / tau := by
  have htau0 : tau ≠ 0 := ne_of_gt htau
  let w : E := (gamma / tau ^ 2) • g
  have hw : w ∈ linearConstraintSet T gamma := by
    change gamma ≤ T w
    change gamma ≤ T ((gamma / tau ^ 2) • g)
    rw [map_smul, hTg]
    simp only [smul_eq_mul]
    have heq : (gamma / tau ^ 2) * tau ^ 2 = gamma := by
      field_simp [htau0]
    exact heq.ge
  have hK : (linearConstraintSet T gamma).Nonempty := ⟨w, hw⟩
  have hlower : gamma / tau ≤
      bestApproximationError (0 : E) (linearConstraintSet T gamma) := by
    apply bestApproximationError_lower_of_coefficientDefect
      (0 : E) (linearConstraintSet T gamma) T gamma tau hK htau
    · exact hTnorm.le
    · intro v hv
      change gamma ≤ |T ((0 : E) - v)|
      have hTv : gamma ≤ T v := hv
      have hTv0 : 0 ≤ T v := hgamma.trans hTv
      simpa [map_neg, abs_neg, abs_of_nonneg hTv0] using hTv
  have hwNorm : ‖(0 : E) - w‖ = gamma / tau := by
    change ‖w‖ = gamma / tau
    rw [show w = (gamma / tau ^ 2) • g by rfl, norm_smul,
      Real.norm_eq_abs, hgnorm]
    have hscale : 0 ≤ gamma / tau ^ 2 :=
      div_nonneg hgamma (sq_nonneg tau)
    rw [abs_of_nonneg hscale]
    field_simp [htau0]
  have hupper : bestApproximationError (0 : E)
      (linearConstraintSet T gamma) ≤ gamma / tau :=
    bestApproximationError_upper_of_witness
      (0 : E) w (linearConstraintSet T gamma) (gamma / tau) hw hwNorm.le
  exact le_antisymm hupper hlower

end LinearConstraint

section ExactLimit

/-- Squeeze theorem specialized to a normalized approximation error whose
upper and lower constants differ by a vanishing remainder. -/
theorem exactAsymptotic_of_eventual_sandwich
    (F eps : ℕ → ℝ) (c : ℝ)
    (heps : Tendsto eps atTop (𝓝 0))
    (hlower : ∀ᶠ n in atTop, c ≤ F n)
    (hupper : ∀ᶠ n in atTop, F n ≤ c + eps n) :
    Tendsto F atTop (𝓝 c) := by
  exact tendsto_of_tendsto_of_tendsto_of_le_of_le'
    tendsto_const_nhds (tendsto_const_nhds.add heps) hlower hupper

/-- Normalize a mesh-dependent best error by its quadratic contact scale. -/
def normalizedQuadraticError (E h : ℕ → ℝ) (n : ℕ) : ℝ :=
  E n / (h n) ^ 2

/-- Exact quadratic asymptotic from matching normalized bounds. -/
theorem normalizedQuadraticError_tendsto
    (E h eps : ℕ → ℝ) (c : ℝ)
    (heps : Tendsto eps atTop (𝓝 0))
    (hlower : ∀ᶠ n in atTop, c ≤ normalizedQuadraticError E h n)
    (hupper : ∀ᶠ n in atTop,
      normalizedQuadraticError E h n ≤ c + eps n) :
    Tendsto (normalizedQuadraticError E h) atTop (𝓝 c) := by
  exact exactAsymptotic_of_eventual_sandwich
    (normalizedQuadraticError E h) eps c heps hlower hupper

/-- The predicted norm of the normalized one-dimensional Green profile for
point evaluation in `H₀¹(-1,1)` with inner product `∫(uv + u'v')`. -/
def greenTraceProfileNorm : ℝ :=
  Real.sqrt (2 / Real.tanh 1)

/-- Predicted sharp coefficient-cone asymptotic constant. -/
def smoothContactGreenConstant (gamma : ℝ) : ℝ :=
  gamma * greenTraceProfileNorm

/-- Terminal exact-limit bridge for the Green-profile constant. -/
theorem smoothContactGreenConstant_tendsto
    (E h eps : ℕ → ℝ) (gamma : ℝ)
    (heps : Tendsto eps atTop (𝓝 0))
    (hlower : ∀ᶠ n in atTop,
      smoothContactGreenConstant gamma ≤ normalizedQuadraticError E h n)
    (hupper : ∀ᶠ n in atTop,
      normalizedQuadraticError E h n ≤
        smoothContactGreenConstant gamma + eps n) :
    Tendsto (normalizedQuadraticError E h) atTop
      (𝓝 (smoothContactGreenConstant gamma)) := by
  exact normalizedQuadraticError_tendsto E h eps
    (smoothContactGreenConstant gamma) heps hlower hupper

end ExactLimit

end

end BernsteinObstacle
