import BernsteinObstacle.MinkowskiRate
import Mathlib.Tactic

namespace BernsteinObstacle

/-!
# Consistency-limited vanishing order and quadratic-contact saturation

The coefficient repair amplitude is controlled by both the coefficient-to-value
consistency order `m` and the physical gap vanishing order `q`.  On an unfitted
mesh the effective amplitude order is therefore `min m q`.

In particular, quadratic contact saturates at order two: once `m >= 2`, raising
polynomial or coefficient consistency order does not change the positive-basis
clipping scale.  Across a codimension-one interface the resulting scale remains
`h * sqrt h`, i.e. `h^(3/2)`.
-/

/-- Effective coefficient amplitude order: approximation consistency cannot
beat the physical vanishing order on a cut element. -/
def consistencyLimitedOrder (m q : ℕ) : ℕ := min m q

/-- If coefficient consistency is at least the physical vanishing order, the
physical vanishing order controls the clipping amplitude. -/
theorem consistencyLimitedOrder_eq_vanishingOrder
    (m q : ℕ) (hqm : q ≤ m) :
    consistencyLimitedOrder m q = q := by
  simp [consistencyLimitedOrder, Nat.min_eq_right hqm]

/-- Positive-basis repair scale after limiting the nominal consistency order by
the physical gap vanishing order. -/
def consistencyVanishingCodimensionScale
    (h : ℝ) (m q c : ℕ) : ℝ :=
  vanishingCodimensionScale h (consistencyLimitedOrder m q) c

/-- In the saturation regime `q <= m`, the consistency-limited scale is exactly
the vanishing-order/codimension scale. -/
theorem consistencyVanishingCodimensionScale_of_q_le_m
    (h : ℝ) (m q c : ℕ) (hqm : q ≤ m) :
    consistencyVanishingCodimensionScale h m q c =
      vanishingCodimensionScale h q c := by
  simp [consistencyVanishingCodimensionScale,
    consistencyLimitedOrder_eq_vanishingOrder m q hqm]

/-- Quadratic contact saturates: every consistency order `m >= 2` gives the
same codimension-one `h^(3/2)` clipping scale. -/
theorem quadraticContact_codimOne_saturation
    (h : ℝ) (m : ℕ) (hm : 2 ≤ m) :
    consistencyVanishingCodimensionScale h m 2 1 =
      h * Real.sqrt h := by
  rw [consistencyVanishingCodimensionScale_of_q_le_m h m 2 1 hm]
  exact vanishingCodimensionScale_quadratic_codimOne h

/-- Exact middle Bernstein coefficient for the phase-locked quadratic cut-cell
model when the midpoint lies in the contact region. -/
def phaseLockedQuadraticMiddleCoefficient (h theta : ℝ) : ℝ :=
  -((1 : ℝ) / 2) * (1 - theta) ^ 2 * h ^ 2

/-- The middle coefficient is strictly negative for a nondegenerate cut cell. -/
theorem phaseLockedQuadraticMiddleCoefficient_neg
    (h theta : ℝ) (hh : 0 < h) (htheta : theta < 1) :
    phaseLockedQuadraticMiddleCoefficient h theta < 0 := by
  have hgap : 0 < 1 - theta := sub_pos.mpr htheta
  have hgapSq : 0 < (1 - theta) ^ 2 := sq_pos_of_pos hgap
  have hhSq : 0 < h ^ 2 := sq_pos_of_pos hh
  have hprod : 0 < (1 - theta) ^ 2 * h ^ 2 := mul_pos hgapSq hhSq
  unfold phaseLockedQuadraticMiddleCoefficient
  nlinarith

/-- The exact symbolic correction profile generated by clipping the negative
middle coefficient in the phase-locked quadratic model. -/
def phaseLockedQuadraticCorrection (h theta x : ℝ) : ℝ :=
  (1 - theta) ^ 2 * x * (h - x)

/-- Algebraic derivative profile of the exact quadratic clipping correction.
This theorem records the polynomial identity used by the exact integral
sharpness calculation. -/
theorem phaseLockedQuadraticCorrection_slope_identity
    (h theta x : ℝ) :
    (1 - theta) ^ 2 * (h - 2 * x) =
      (1 - theta) ^ 2 * (h - x) - (1 - theta) ^ 2 * x := by
  ring

end BernsteinObstacle
