#!/usr/bin/env python3
"""Emit complete boundary-regime CNFs for the exact n=22 target-34 problem."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from pysat.card import CardEnc, EncType
from pysat.formula import IDPool

import n22_data as data
import n22_exact_core as core


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("regime", choices=("all-double", "top-low"))
    parser.add_argument("output", type=Path)
    parser.add_argument("--manifest", type=Path, required=True)
    args = parser.parse_args()

    pool = IDPool(start_from=len(data.P) + 1)
    cnf, info = core.base_cnf(pool)

    if args.regime == "all-double":
        for ids in data.BIDS.values():
            cnf.extend(CardEnc.equals(ids, 2, vpool=pool, encoding=EncType.seqcounter).clauses)
        restriction = "each of top,left,rb,rr has exactly two selected points"
    else:
        cnf.extend(CardEnc.atmost(data.BIDS["top"], 1, vpool=pool,
                                  encoding=EncType.seqcounter).clauses)
        restriction = "top border has at most one selected point"

    cnf.nv = max(cnf.nv, pool.top)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    cnf.to_file(str(args.output))

    manifest = {
        "board_side": 22,
        "parity": 0,
        "target_points": 34,
        "regime": args.regime,
        "restriction": restriction,
        "variables": cnf.nv,
        "clauses": len(cnf.clauses),
        "weighted_slack_encoding": info,
        "coverage_note": (
            "Every border is a Euclidean line and hence has occupancy at most two. "
            "A target-34 assignment is therefore either all-double or has some border "
            "of occupancy at most one. The parity-preserving symmetries generated by "
            "coordinate swap and 180-degree rotation send every border to the top."
        ),
    }
    args.manifest.write_text(json.dumps(manifest, sort_keys=True, indent=2) + "\n")
    print(json.dumps(manifest, sort_keys=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
