#include <bits/stdc++.h>
using namespace std; using u64 = uint64_t;
struct Key { array<u64,4> w{}; bool operator==(Key const& o) const { return w == o.w; } };
struct Hash { size_t operator()(Key const& k) const { u64 h=0x9e3779b97f4a7c15ULL; for(u64 v:k.w){ v+=0x9e3779b97f4a7c15ULL; v=(v^(v>>30))*0xbf58476d1ce4e5b9ULL; v=(v^(v>>27))*0x94d049bb133111ebULL; v^=v>>31; h^=v+0x9e3779b97f4a7c15ULL+(h<<6)+(h>>2);} return size_t(h); } };
inline bool bit(Key const& k,int n){ return (k.w[n>>6]>>(n&63))&1ULL; }
inline void setb(Key& k,int n){ k.w[n>>6] |= 1ULL<<(n&63); }
inline int pop(Key const& k){ int c=0; for(auto x:k.w)c+=__builtin_popcountll(x); return c; }
inline bool subset(Key const& x,Key const& y){ for(int i=0;i<4;i++)if(x.w[i]&~y.w[i])return false; return true; }
pair<Key,int> gapmask(vector<int> const& g,int L=-1){ int gg=0; for(int x:g)gg=gcd(gg,x); if(gg!=1)throw runtime_error("gcd"); int m=*min_element(g.begin(),g.end()); const long long INF=1e18; vector<long long>d(m,INF); d[0]=0; using P=pair<long long,int>; priority_queue<P,vector<P>,greater<P>>q; q.push({0,0}); while(!q.empty()){auto[du,r]=q.top();q.pop();if(du!=d[r])continue;for(int x:g){long long nd=du+x;int nr=nd%m;if(nd<d[nr]){d[nr]=nd;q.push({nd,nr});}}} int F=int(*max_element(d.begin(),d.end())-m); if(L<0)L=F; if(L>=256)throw runtime_error("F>=256"); Key k; for(int n=1;n<=L;n++)if(n<d[n%m])setb(k,n); return {k,F}; }
struct Solver {
 int F; Key root; double lim; chrono::steady_clock::time_point start; uint64_t nodes=0,hits=0;
 unordered_map<Key,int16_t,Hash> memo; unordered_set<Key,Hash> seedP;
 Solver(int f,Key r,double l):F(f),root(r),lim(l){memo.reserve(1<<22);seedP.reserve(1<<18);start=chrono::steady_clock::now();}
 Key child(Key const& G,int x)const{Key h;for(int r=1;r<=min(x-1,F);r++)for(int n=r;n<=F&&bit(G,n);n+=x)setb(h,n);return h;}
 void loadMemoBin(string const& path){ifstream in(path,ios::binary);if(!in)return;char magic[8];int f;in.read(magic,8);in.read((char*)&f,sizeof(f));if(!in||string(magic,8)!="SYLVMEM1"||f!=F)return;Key k;int16_t v;while(in.read((char*)k.w.data(),sizeof(u64)*4)){in.read((char*)&v,sizeof(v));if(!in)break;if(subset(k,root))memo[k]=v;}}
 void saveMemoBin(string const& path){string tmp=path+".tmp";ofstream out(tmp,ios::binary|ios::trunc);out.write("SYLVMEM1",8);out.write((char*)&F,sizeof(F));for(auto const&[k,v]:memo){out.write((char*)k.w.data(),sizeof(u64)*4);out.write((char*)&v,sizeof(v));}out.close();rename(tmp.c_str(),path.c_str());}
 void loadP(string const& path){ifstream in(path);string line;while(getline(in,line)){istringstream ss(line);vector<int>v;int x;while(ss>>x){if(x==0)break;if(x>1)v.push_back(x);}if(v.empty())continue;try{auto[k,f]=gapmask(v,F);if(subset(k,root))seedP.insert(k);}catch(...){}}}
 int solve(Key const& G){auto it=memo.find(G);if(it!=memo.end()){hits++;return it->second;}if(seedP.count(G)){memo.emplace(G,-1);return-1;}if((++nodes&0x3fff)==0){double s=chrono::duration<double>(chrono::steady_clock::now()-start).count();if(s>lim)throw runtime_error("timeout");}for(int x=2;x<=F;x++)if(bit(G,x)){Key c=child(G,x);if(seedP.count(c)){memo.emplace(G,int16_t(x));return x;}auto jt=memo.find(c);if(jt!=memo.end()&&jt->second==-1){memo.emplace(G,int16_t(x));return x;}}Key paired;for(int x=2;x<=F;x++)if(bit(G,x)){if(bit(paired,x))continue;Key c=child(G,x);int z=solve(c);if(z==-1){memo.emplace(G,int16_t(x));return x;}if(z>x&&z<=F&&bit(G,z))setb(paired,z);}memo.emplace(G,-1);return-1;}
};
int main(int argc,char**argv){if(argc<2){cerr<<"usage: solver generator...\n";return 2;}vector<int>g;for(int i=1;i<argc;i++)g.push_back(stoi(argv[i]));auto[G,Factual]=gapmask(g);int F=Factual;if(getenv("SYLVER_FIXED_F")){F=stoi(getenv("SYLVER_FIXED_F"));G=gapmask(g,F).first;}double lim=getenv("SYLVER_LIMIT")?stod(getenv("SYLVER_LIMIT")):20.0;Solver s(F,G,lim);if(getenv("SYLVER_P_CACHE"))s.loadP(getenv("SYLVER_P_CACHE"));if(getenv("SYLVER_LOAD_MEMO"))s.loadMemoBin(getenv("SYLVER_LOAD_MEMO"));else if(getenv("SYLVER_MEMO_BIN"))s.loadMemoBin(getenv("SYLVER_MEMO_BIN"));s.start=chrono::steady_clock::now();try{int w=s.solve(G);cout<<(w<0?"P":"N move="+to_string(w))<<" nodes="<<s.nodes<<" memo="<<s.memo.size()<<" hits="<<s.hits<<"\n";}catch(exception const&){cout<<"TIMEOUT nodes="<<s.nodes<<" memo="<<s.memo.size()<<" hits="<<s.hits<<"\n";}if(getenv("SYLVER_MEMO_BIN"))s.saveMemoBin(getenv("SYLVER_MEMO_BIN"));}
