-- Corrected API probe trigger for the Lean 4.27 compatibility repair.
import FormalConjectures.Paper.VoronovskajaTypeFormula

#check VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators
#check VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.eventually_smooth
#check VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.eventually_smooth.limit_exists
#check VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.answer_smoothness

#print axioms VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators
#print axioms VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.eventually_smooth
#print axioms VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.eventually_smooth.limit_exists
#print axioms VoronovskajaTypeFormula.voronovskaja_theorem.bezier_bernstein_operators.variants.answer_smoothness
