name = "voronovskaja_audit"
defaultTargets = ["Audit"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/DomTheDeveloper/formal-conjectures.git"
rev = "8808d2ddbb3a307d4c8dce969ac1484c16b6b5e8"

[[lean_lib]]
name = "Audit"
globs = ["Audit"]
