name = "voronovskaja_audit"
defaultTargets = ["Audit"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/DomTheDeveloper/formal-conjectures.git"
rev = "f3d6103b0845c168c27d8f9fdd4e1067484eb575"

[[lean_lib]]
name = "Audit"
globs = ["Audit"]
