name = "voronovskaja_audit"
defaultTargets = ["Audit"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/DomTheDeveloper/formal-conjectures.git"
rev = "82cafd807c69c86eda8fda8a6d6e0dcac2ee11de"

[[lean_lib]]
name = "Audit"
globs = ["Audit"]
