import Checkerboard.CubicTransform
import Checkerboard.FiniteContradictions
import Checkerboard.CeilingAlgebra
import Checkerboard.MasterAlgebra
import Checkerboard.LP.AlgebraicParameter
import Checkerboard.LP.FiniteModel
