#!/usr/bin/env python3
"""Screen the rank-two quotient image of the four-row curve over Q_2.

We enumerate integral Q_2 disks by u0 modulo 2^N, construct exact Q_2 points
where the three remaining square conditions hold, and compare their Kummer
classes with the localized global Mordell--Weil classes and with the rank-one
subgroup generated by the non-torsion localization-kernel class.
"""
from __future__ import annotations
import itertools,json,traceback
from pathlib import Path
from sage.all import Qp,QQ,Integer
import sage_kummer_compat as kc
from sage_unified_descent import point_json
N=14
PREC=100

def sc(z):
    if z==0:return '0'
    v=int(z.valuation());u=z/(z.parent()(2)**v)
    # Odd unit squareclass is determined modulo 8.
    a=int(u.add_bigoh(3).lift())%8
    return f'{v&1}:{a}'
def kummer(P,p,q):
    if P.is_zero():return ('0:1','0:1')
    x=P[0]
    if x!=0 and x!=-4*p and x!=-4*q:return (sc(x),sc(x+4*p))
    K=P.curve().base_field()
    if x==0:return (sc(K(p*q)),sc(K(p)))
    if x==-4*p:return (sc(K(-p)),sc(K(-p*(q-p))))
    return (sc(K(-q)),sc(K(-(q-p))))
def qpoint(E,u,v,w):return E(4*(v-u)*(w-u),8*(v-u)*(w-u)*(v+w))

def main():
    E0,p0,q0=kc.input_curve(kc.TRIPLES[0]);gens,rank=kc.certified_basis_on_input(E0);tors=[E0(0,0),E0(-4*p0,0)]
    K=Qp(2,prec=PREC,type='capped-rel');E=E0.change_ring(K);p=K(p0);q=K(q0)
    s=K(Integer(3222)^2-Integer(2578)^2)
    global_classes=[]
    for free in itertools.product([0,1],repeat=rank):
      P=E0(0)
      for b,G in zip(free,gens):
        if b:P+=G
      for tb in itertools.product([0,1],repeat=2):
        Q=P
        for b,T in zip(tb,tors):
          if b:Q+=T
        global_classes.append({'free':free,'torsion':tb,'label':kummer(E(Q),p,q),'point':point_json(Q)})
    labels_to_global={}
    for c in global_classes:labels_to_global.setdefault(c['label'],[]).append(c)
    kernel=[c for c in global_classes if c['free']==(0,1) and c['torsion']==(1,0)][0]
    # Gamma=<kernel representative, rational 2-torsion> modulo 2.
    gamma_labels=set()
    R=E0(kernel['point']) if False else None
    for rb in [0,1]:
      for tb in itertools.product([0,1],repeat=2):
        P=E0(0)
        if rb:
          # Reconstruct the kernel representative from its stored bits.
          P+=gens[1]+tors[0]
        for b,T in zip(tb,tors):
          if b:P+=T
        gamma_labels.add(kummer(E(P),p,q))
    local_labels=set();examples={};tested=0;admissible_u=0;errors=[]
    for a in range(1<<N):
      u=K(a);vals=[u*u+p,u*u+q,u*u+s]
      try:
        if not all(z.is_square() for z in vals):continue
        roots=[z.sqrt() for z in vals];admissible_u+=1
        for signs in itertools.product([1,-1],repeat=3):
          v=signs[0]*roots[0];w=signs[1]*roots[1]
          P=qpoint(E,u,v,w);lab=kummer(P,p,q);local_labels.add(lab)
          examples.setdefault(str(lab),{'u':str(u),'v':str(v),'w':str(w),'fourth_root':str(signs[2]*roots[2])})
          tested+=1
      except Exception as exc:errors.append(f'{type(exc).__name__}: {exc}')
    # Add all eight projective infinity sign points.
    for tail in itertools.product([1,-1],repeat=2):
      signs=(1,)+tail
      P=kc.infinity_image(E,p,q,signs[0],signs[1],signs[2]);local_labels.add(kummer(P,p,q))
    global_image=set(labels_to_global);forbidden_global=global_image-gamma_labels
    out={'N':N,'precision':PREC,'rank':rank,'global_class_count':len(global_classes),
      'global_local_label_count':len(global_image),'gamma_local_label_count':len(gamma_labels),
      'forbidden_global_label_count':len(forbidden_global),'admissible_u_residues':admissible_u,
      'sampled_local_points':tested,'local_curve_label_count':len(local_labels),
      'local_curve_labels':[list(x) for x in sorted(local_labels)],
      'global_labels':[list(x) for x in sorted(global_image)],
      'gamma_labels':[list(x) for x in sorted(gamma_labels)],
      'forbidden_global_labels':[list(x) for x in sorted(forbidden_global)],
      'forbidden_seen_in_curve_image':[list(x) for x in sorted(forbidden_global&local_labels)],
      'zeroth_level_condition_holds':not bool(forbidden_global&local_labels),
      'examples':examples,'errors':sorted(set(errors)),
      'caveat':'This is a stabilized finite-precision disk screen, not yet the recursive q-set proof required by Stoll.'}
    Path('results').mkdir(exist_ok=True);Path('results/rank2_local_image.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({k:out[k] for k in ['global_local_label_count','gamma_local_label_count','forbidden_global_label_count','local_curve_label_count','forbidden_seen_in_curve_image','zeroth_level_condition_holds','admissible_u_residues']}))
if __name__=='__main__':main()
