#!/usr/bin/env python3
"""Certify the subgroup generated by the 56 known projective point images.

Each quotient point is expressed exactly in one certified Mordell--Weil basis by
bounded exhaustive search and exact point equality. Integer linear algebra then
computes the free rank, saturation index, and mod-2 span including torsion.
"""
from __future__ import annotations
import itertools,json
from pathlib import Path
from sage.all import GF,Matrix,ZZ,proof
from sage_unified_descent import certified_factor_data,known_projective_points,point_json

BOUND=6

def pkey(P):
    return ('O',) if P.is_zero() else (str(P[0]),str(P[1]),str(P[2]))

def coordinate_dictionary(FD):
    E=FD['E'];gs=FD['gens'];ts=FD['tors'];d={};collisions=0
    multiples=[[c*G for c in range(-BOUND,BOUND+1)] for G in gs]
    for shifted in itertools.product(range(2*BOUND+1),repeat=len(gs)):
        coeff=tuple(i-BOUND for i in shifted);P=E(0)
        for i,ms in zip(shifted,multiples):P+=ms[i]
        for tb in itertools.product([0,1],repeat=2):
            Q=P
            for b,T in zip(tb,ts):
                if b:Q+=T
            k=pkey(Q);rec={'coeffs':coeff,'torsion':tb}
            if k in d and d[k]!=rec:collisions+=1
            d[k]=rec
    return d,collisions

def gf2_rank(rows):
    return 0 if not rows else Matrix(GF(2),rows).rank()

def main():
    proof.all(True);factors=certified_factor_data();known=known_projective_points(factors)
    dicts=[];dict_report=[]
    for FD in factors:
        d,col=coordinate_dictionary(FD);dicts.append(d)
        dict_report.append({'kind':FD['kind'],'indices':list(FD.get('inds',())),'rank':FD['rank'],
                            'dictionary_size':len(d),'collisions':col})
    coordinates=[];missing=[]
    for K in known:
        free=[];tors=[]
        for f,Q in enumerate(K['points']):
            rec=dicts[f].get(pkey(Q))
            if rec is None:
                missing.append({'point':K['id'],'factor':f,'quotient_point':point_json(Q)})
                free.extend([None]*factors[f]['rank']);tors.extend([None,None])
            else:
                free.extend(rec['coeffs']);tors.extend(rec['torsion'])
        coordinates.append({'id':K['id'],'free':free,'torsion':tors})
    if missing:
        out={'bound':BOUND,'missing':missing,'dictionaries':dict_report}
        Path('results').mkdir(exist_ok=True);Path('results/known_subgroup.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
        raise RuntimeError(f'{len(missing)} known quotient points outside coordinate bound')
    base=coordinates[0];free_rows=[];tors_rows=[]
    for C in coordinates[1:]:
        free_rows.append([ZZ(a)-ZZ(b) for a,b in zip(C['free'],base['free'])])
        tors_rows.append([(int(a)-int(b))&1 for a,b in zip(C['torsion'],base['torsion'])])
    M=Matrix(ZZ,free_rows);free_rank=M.rank();L=M.row_module(ZZ);Sat=L.saturation()
    S=M.smith_form();diag=[abs(ZZ(S[i,i])) for i in range(min(S.nrows(),S.ncols())) if S[i,i]!=0]
    smith_index=ZZ.prod(diag) if diag else ZZ(1)
    combined=[[int(x)&1 for x in fr]+tr for fr,tr in zip(free_rows,tors_rows)]
    out={'bound':BOUND,'known_point_count':len(known),'factor_ranks':[FD['rank'] for FD in factors],
      'total_free_rank':sum(FD['rank'] for FD in factors),'dictionaries':dict_report,
      'missing_count':0,'coordinates':coordinates,
      'known_difference_free_rank':free_rank,'known_difference_torsion_mod2_rank':gf2_rank(tors_rows),
      'known_difference_combined_mod2_rank':gf2_rank(combined),
      'free_saturation_rank':Sat.rank(),'free_saturation_index_via_smith':str(smith_index),
      'smith_nonzero_diagonal':[str(x) for x in diag],
      'free_row_basis':[list(map(int,row)) for row in L.basis()],
      'saturated_free_basis':[list(map(int,row)) for row in Sat.basis()],
      'interpretation':'All coordinates are proved by exact elliptic-curve point equality. Rank and Smith data are exact integer linear algebra.'}
    Path('results').mkdir(exist_ok=True);Path('results/known_subgroup.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n')
    print(json.dumps({k:out[k] for k in ['known_difference_free_rank','known_difference_torsion_mod2_rank','known_difference_combined_mod2_rank','free_saturation_index_via_smith','missing_count']}))
if __name__=='__main__':main()
