name = "wotw316"
defaultTargets = ["WotW316", "WotW316Count"]

[[require]]
name = "formal_conjectures"
git = "https://github.com/google-deepmind/formal-conjectures.git"
rev = "b2e608fc52d765510915a244bb69b1a2741acc3c"

[[lean_lib]]
name = "WotW316"

[[lean_lib]]
name = "WotW316Count"
